### ISSUE TITLE
http的demo服务重启就报一下错误

### ISSUE THREAD

**Issue by netaxcess** [deepfabric/beehive#2]
第一次启动正常，第二次重启服务，运行一下命令：go run example/http/main.go -beehive-cfg=./beehive-1.toml -addr=127.0.0.1:6371**

提示一下错误

2020/04/26 16:10:12.516927 [info] [prophet]: ********become to leader now********
2020/04/26 16:10:12.547843 [info] [beehive-raftstore]: *********Become prophet leader*********
2020/04/26 16:10:12.547843 [info] [beehive-raftstore]: create 3 shards on bootstrap the cluster
------------------
<nil>
------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xe1997b]

goroutine 218 [running]:
github.com/deepfabric/beehive/storage/badger.(*Storage).Get(0x0, 0x1a7b17c, 0x2, 0x2, 0x0, 0x0, 0x4, 0x108e9de, 0x2)
        F:/golang/src/github.com/deepfabric/beehive/storage/badger/storage.go:82 +0x8b
github.com/deepfabric/beehive/raftstore.(*store).doBootstrapCluster(0xc000290900)
        F:/golang/src/github.com/deepfabric/beehive/raftstore/prophet_adapter.go:40 +0x22e
github.com/deepfabric/beehive/raftstore.(*store).ProphetBecomeLeader.func1()
        F:/golang/src/github.com/deepfabric/beehive/raftstore/prophet_adapter.go:20 +0x36
sync.(*Once).Do(0xc000290990, 0xc005955978)
        C:/Go/src/sync/once.go:44 +0xba
github.com/deepfabric/beehive/raftstore.(*store).ProphetBecomeLeader(0xc000290900)
        F:/golang/src/github.com/deepfabric/beehive/raftstore/prophet_adapter.go:19 +0xa0
github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet.(*defaultProphet).enableLeader(0xc005bc20d0)
        F:/golang/src/github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet/prophet_leader.go:69 +0x3c0
github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet.(*defaultProphet).enableLeader-fm()
        F:/golang/src/github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet/prophet_leader.go:47 +0x31
github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet.(*elector).campaignLeader(0xc000126480, 0x11d9ce0, 0xc000067f40, 0xffffffffffffffff, 0xc0000ac690, 0x28, 0xc0001f68d0, 0xc0001f68e0, 0x0, 0x0)
        F:/golang/src/github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet/election.go:282 +0x666
github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet.(*elector).ElectionLoop(0xc000126480, 0x11d9ce0, 0xc000067f40, 0xffffffffffffffff, 0xc0000ac690, 0x28, 0xc0001f68d0, 0xc0001f68e0)
        F:/golang/src/github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet/election.go:143 +0x6eb
created by github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet.(*defaultProphet).startLeaderLoop
        F:/golang/src/github.com/deepfabric/beehive/vendor/github.com/deepfabric/prophet/prophet_leader.go:44 +0x195

**Comment by zhangxu19830126** [comment]
加上--data参数指定数据存储的位置
